run:
  timeout: 5m

linters:
  disable:
    - errcheck
  enable:
    - govet
    - staticcheck
    - ineffassign
    - misspell
    - unused
    - gofmt

linters-settings:
  gofmt:
    simplify: true
