// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckForUpdates() {
  return window['go']['main']['App']['CheckForUpdates']();
}

export function ClearIndex() {
  return window['go']['main']['App']['ClearIndex']();
}

export function CloseSettings() {
  return window['go']['main']['App']['CloseSettings']();
}

export function CompleteOnboarding(arg1) {
  return window['go']['main']['App']['CompleteOnboarding'](arg1);
}

export function Execute(arg1) {
  return window['go']['main']['App']['Execute'](arg1);
}

export function ExecuteContextAction(arg1, arg2) {
  return window['go']['main']['App']['ExecuteContextAction'](arg1, arg2);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetContextActions(arg1) {
  return window['go']['main']['App']['GetContextActions'](arg1);
}

export function GetIcon(arg1) {
  return window['go']['main']['App']['GetIcon'](arg1);
}

export function GetIndexStatus() {
  return window['go']['main']['App']['GetIndexStatus']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function HideWindow() {
  return window['go']['main']['App']['HideWindow']();
}

export function InstallUpdate() {
  return window['go']['main']['App']['InstallUpdate']();
}

export function IsFirstRun() {
  return window['go']['main']['App']['IsFirstRun']();
}

export function IsSettingsMode() {
  return window['go']['main']['App']['IsSettingsMode']();
}

export function OpenSettingsWindow() {
  return window['go']['main']['App']['OpenSettingsWindow']();
}

export function RefreshApps() {
  return window['go']['main']['App']['RefreshApps']();
}

export function ReindexFiles() {
  return window['go']['main']['App']['ReindexFiles']();
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function GetStartupEnabled() {
  return window['go']['main']['App']['GetStartupEnabled']();
}

export function Search(arg1) {
  return window['go']['main']['App']['Search'](arg1);
}

export function ShowWindow() {
  return window['go']['main']['App']['ShowWindow']();
}

export function ToggleWindow() {
  return window['go']['main']['App']['ToggleWindow']();
}
