// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelIndex() {
  return window['go']['main']['App']['CancelIndex']();
}

export function CheckForUpdates() {
  return window['go']['main']['App']['CheckForUpdates']();
}

export function ClearIndex() {
  return window['go']['main']['App']['ClearIndex']();
}

export function CloseSettings() {
  return window['go']['main']['App']['CloseSettings']();
}

export function CompleteOnboarding(arg1, arg2, arg3) {
  return window['go']['main']['App']['CompleteOnboarding'](arg1, arg2, arg3);
}

export function DeleteAlias(arg1) {
  return window['go']['main']['App']['DeleteAlias'](arg1);
}

export function Execute(arg1) {
  return window['go']['main']['App']['Execute'](arg1);
}

export function ExecuteContextAction(arg1, arg2) {
  return window['go']['main']['App']['ExecuteContextAction'](arg1, arg2);
}

export function ExportSettings() {
  return window['go']['main']['App']['ExportSettings']();
}

export function GetAliases() {
  return window['go']['main']['App']['GetAliases']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetContextActions(arg1) {
  return window['go']['main']['App']['GetContextActions'](arg1);
}

export function GetDataDir() {
  return window['go']['main']['App']['GetDataDir']();
}

export function GetIcon(arg1) {
  return window['go']['main']['App']['GetIcon'](arg1);
}

export function GetIndexStatus() {
  return window['go']['main']['App']['GetIndexStatus']();
}

export function GetInstallDir() {
  return window['go']['main']['App']['GetInstallDir']();
}

export function GetStartupEnabled() {
  return window['go']['main']['App']['GetStartupEnabled']();
}

export function GetUsageScores() {
  return window['go']['main']['App']['GetUsageScores']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function HideWindow() {
  return window['go']['main']['App']['HideWindow']();
}

export function ImportSettings(arg1) {
  return window['go']['main']['App']['ImportSettings'](arg1);
}

export function InstallUpdate() {
  return window['go']['main']['App']['InstallUpdate']();
}

export function IsFirstRun() {
  return window['go']['main']['App']['IsFirstRun']();
}

export function IsSettingsMode() {
  return window['go']['main']['App']['IsSettingsMode']();
}

export function OpenFolder(arg1) {
  return window['go']['main']['App']['OpenFolder'](arg1);
}

export function OpenURL(arg1) {
  return window['go']['main']['App']['OpenURL'](arg1);
}

export function OpenFolderPicker() {
  return window['go']['main']['App']['OpenFolderPicker']();
}

export function OpenSettingsWindow() {
  return window['go']['main']['App']['OpenSettingsWindow']();
}

export function RefreshApps() {
  return window['go']['main']['App']['RefreshApps']();
}

export function ReindexFiles() {
  return window['go']['main']['App']['ReindexFiles']();
}

export function SaveAlias(arg1, arg2) {
  return window['go']['main']['App']['SaveAlias'](arg1, arg2);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function Search(arg1) {
  return window['go']['main']['App']['Search'](arg1);
}

export function ShowWindow() {
  return window['go']['main']['App']['ShowWindow']();
}

export function TogglePinned(arg1) {
  return window['go']['main']['App']['TogglePinned'](arg1);
}

export function ToggleWindow() {
  return window['go']['main']['App']['ToggleWindow']();
}

export function Uninstall() {
  return window['go']['main']['App']['Uninstall']();
}
